"""initial

Revision ID: 65cd3f1fe173
Revises: 
Create Date: 2025-10-15 23:04:41.122214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cd3f1fe173'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_data', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_schema_version', 'characters', ['schema_version'], unique=False)
    op.create_index('idx_character_updated_at', 'characters', ['updated_at'], unique=False)
    op.create_index('idx_user_characters', 'characters', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('conversation', 'evaluation')", name='check_message_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_session', 'messages', ['character_id', 'session_id'], unique=False)
    op.create_index('idx_session_created_at', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_session_offset', 'messages', ['session_id', 'offset'], unique=False)
    op.create_index('idx_user_sessions', 'messages', ['user_id', 'session_id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_session_summaries', 'summaries', ['character_id', 'session_id'], unique=False)
    op.create_index('idx_session_created_at_summaries', 'summaries', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_session_offsets', 'summaries', ['session_id', 'start_offset', 'end_offset'], unique=False)
    op.create_index('idx_user_summaries', 'summaries', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_summaries', table_name='summaries')
    op.drop_index('idx_session_offsets', table_name='summaries')
    op.drop_index('idx_session_created_at_summaries', table_name='summaries')
    op.drop_index('idx_character_session_summaries', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index('idx_user_sessions', table_name='messages')
    op.drop_index('idx_session_offset', table_name='messages')
    op.drop_index('idx_session_created_at', table_name='messages')
    op.drop_index('idx_character_session', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_user_characters', table_name='characters')
    op.drop_index('idx_character_updated_at', table_name='characters')
    op.drop_index('idx_character_schema_version', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
