"""add_is_persona_to_characters

Revision ID: d8e959f60e34
Revises: 65cd3f1fe173
Create Date: 2025-10-27 01:57:35.004250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e959f60e34'
down_revision: Union[str, Sequence[str], None] = '65cd3f1fe173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_persona', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_persona')
    # ### end Alembic commands ###
