from typing import Any

from pydantic import BaseModel, Field

from .character import Character, PartialCharacter
from .simulation import (
    ContinuationOption,
    Ruleset,
    WorldLore,
    WorldState,
)


class CharacterSummary(BaseModel):
    """Summary model for character listing with minimal data."""

    id: str = Field(..., description="Character ID")
    name: str = Field(..., description="Character name")
    tagline: str = Field(..., description="Character tagline/description")


class CreateCharacterRequest(BaseModel):
    """Request model for creating a character card."""

    data: Character | str = Field(..., description="Either structured character data or freeform YAML text")
    is_yaml_text: bool = Field(False, description="Set to true if 'data' contains freeform YAML text")
    is_persona: bool = Field(False, description="Set to true if this character is a persona (user character)")


class CreateCharacterResponse(BaseModel):
    """Response model for character creation."""

    message: str
    character_filename: str


class SessionInfo(BaseModel):
    session_id: str
    character_name: str
    message_count: int
    last_message_time: str
    last_character_response: str | None = None
    scenario_name: str | None = None
    turn_count: int | None = None


class SessionMessage(BaseModel):
    role: str
    content: str
    created_at: str


class SessionDetails(BaseModel):
    session_id: str
    character_name: str
    message_count: int
    last_messages: list[SessionMessage]
    last_message_time: str


class InteractRequest(BaseModel):
    """Legacy interact request — retained until old pipeline is removed."""

    character_name: str = Field(..., min_length=1, description="Name of the character to interact with")
    user_message: str = Field(..., min_length=1, description="User's message to the character")
    session_id: str | None = Field(None, description="Optional session ID for conversation continuity")
    processor_type: str = Field("google", description="AI processor type (google, openai, cohere, etc.)")
    backup_processor_type: str | None = Field(None, description="Optional backup processor type to use if primary fails")


class SessionSummaryResponse(BaseModel):
    """Legacy session summary response — retained until old pipeline is removed."""

    session_id: str = Field(..., description="The session ID")
    summary_text: str = Field(..., description="Formatted summary text")
    has_summary: bool = Field(..., description="Whether the session has any summaries")


class HealthStatus(BaseModel):
    status: str
    conversation_memory: str
    details: dict[str, str] | None = None


class ErrorResponse(BaseModel):
    error: str
    detail: str


class ThinkingEvent(BaseModel):
    type: str = "thinking"
    stage: str = Field(..., description="Current processing stage")


class StreamEvent(BaseModel):
    type: str = Field(..., description="Event type: 'chunk', 'session', 'error', 'complete', 'thinking', 'stage', 'dice', 'narration_chunk', 'narration_complete', 'options', 'world_state', 'turn_complete'")
    content: str | None = None
    session_id: str | None = None
    error: str | None = None
    full_response: str | None = None
    message_count: int | None = None
    stage: str | None = None
    # New turn pipeline fields
    turn_number: int | None = None
    options: list[ContinuationOption] | None = None
    world_state: WorldState | None = None
    dice_result: dict[str, Any] | None = None


class GenerateCharacterRequest(BaseModel):
    """Request model for generating a character with AI assistance."""

    partial_character: dict[str, str | list[str] | dict[str, str] | None] = Field(default_factory=dict, description="Partial character data with optional fields to be filled by AI")
    processor_type: str = Field(default="claude", description="AI processor type to use for generation (claude, openai, cohere, etc.)")
    backup_processor_type: str | None = Field(None, description="Optional backup processor type to use if primary fails")


class GenerateCharacterResponse(BaseModel):
    """Response model for character generation."""

    character: Character = Field(..., description="Complete generated character")
    generated_fields: list[str] = Field(..., description="List of fields that were generated by AI")


class Scenario(BaseModel):
    """Model for a rich scenario with story development information."""

    summary: str = Field(..., min_length=1, description="Short engaging name for the scenario")
    intro_message: str = Field(..., min_length=1, description="Introductory message to set the scene")

    # Character references — multi-character
    character_ids: list[str] = Field(default_factory=list, description="NPC character IDs in this scenario")
    persona_id: str = Field(default="", description="User persona ID")

    # Ruleset and world lore
    ruleset_id: str = Field(..., min_length=1, description="References a Ruleset")
    lore_ids: list[str] = Field(default_factory=list, description="References selected WorldLore entries")

    # Location/Setting
    location: str = Field(default="", description="Starting location")
    time_context: str = Field(default="", description="Starting time/situation")
    atmosphere: str = Field(default="", description="Mood/atmosphere description")

    # Story structure
    plot_hooks: list[str] = Field(default_factory=list, description="Key tensions/conflicts (2-4 items)")
    stakes: str = Field(default="", description="What's at risk")
    character_goals: dict[str, str] = Field(default_factory=dict, description="{character_name: goal}")
    potential_directions: list[str] = Field(default_factory=list, description="Where the story could go")

    # Starting world state
    starting_world_state: WorldState | None = Field(default=None, description="Initial world state")

    # Per-character starting state overrides for this scenario
    character_starting_overrides: dict[str, dict[str, Any]] = Field(
        default_factory=dict,
        description="{char_id: {drives: {...}, skills: {...}, emotional_state: {...}}}",
    )



class StartSessionRequest(BaseModel):
    """Request model for starting a session with a scenario."""

    scenario_id: str = Field(..., min_length=1, description="ID of a stored scenario to use")
    processor_type: str = Field(default="google", description="Large model processor type")
    mini_processor_type: str | None = Field(default=None, description="Mini model processor type")
    backup_processor_type: str | None = Field(None, description="Optional backup processor type")


class StartSessionResponse(BaseModel):
    """Response model for starting a session."""

    session_id: str = Field(..., description="The created session ID")


class ChatMessageModel(BaseModel):
    """Model for a chat message in character creation."""

    author: str = Field(..., description="Author of the message (User or AI)")
    content: str = Field(..., description="Content of the message")
    is_user: bool = Field(..., description="Whether this message is from the user")


class CharacterCreationRequest(BaseModel):
    """Request model for interactive character creation with AI assistant."""

    user_message: str = Field(..., min_length=1, description="User's message describing the character")
    current_character: PartialCharacter = Field(default_factory=dict, description="Current partial character data")
    conversation_history: list[ChatMessageModel] = Field(default_factory=list, description="Previous conversation messages")
    processor_type: str = Field(default="claude", description="AI processor type to use")
    backup_processor_type: str | None = Field(None, description="Optional backup processor type")


class CharacterCreationStreamEvent(BaseModel):
    """Stream event for character creation."""

    type: str = Field(..., description="Event type: 'message', 'update', 'complete', 'error'")
    message: str | None = Field(None, description="AI message chunk to show in chat")
    updates: PartialCharacter | None = Field(None, description="Updated character state with current values")
    error: str | None = Field(None, description="Error message if type is 'error'")



class PersonaSummary(BaseModel):
    """Summary of a persona for the AI to consider."""

    id: str = Field(..., description="Persona ID")
    name: str = Field(..., description="Persona name")
    tagline: str = Field(default="", description="Short persona description")
    personality: str = Field(default="", description="Personality traits")


class PartialScenario(BaseModel):
    """Partial scenario for incremental updates during interactive creation."""

    summary: str = Field(default="", description="Short engaging name for the scenario")
    intro_message: str = Field(default="", description="Introductory message to set the scene")
    character_ids: list[str] = Field(default_factory=list, description="NPC character IDs")
    persona_id: str | None = Field(None, description="Optional user persona ID")
    suggested_persona_id: str | None = Field(None, description="AI-suggested persona ID")
    suggested_persona_reason: str = Field(default="", description="Reason for persona suggestion")
    ruleset_id: str = Field(default="", description="Ruleset ID")
    lore_ids: list[str] = Field(default_factory=list, description="WorldLore entry IDs")
    location: str = Field(default="", description="Starting location")
    time_context: str = Field(default="", description="Starting time/situation")
    atmosphere: str = Field(default="", description="Mood/atmosphere description")
    plot_hooks: list[str] = Field(default_factory=list, description="Key tensions/conflicts")
    stakes: str = Field(default="", description="What's at risk")
    character_goals: dict[str, str] = Field(default_factory=dict, description="{character_name: goal}")
    potential_directions: list[str] = Field(default_factory=list, description="Where the story could go")


class ScenarioCreationRequest(BaseModel):
    """Request model for interactive scenario creation with AI assistant."""

    user_message: str = Field(..., min_length=1, description="User's message about the scenario")
    current_scenario: PartialScenario = Field(default_factory=PartialScenario, description="Current partial scenario data")
    character_name: str = Field(..., min_length=1, description="Name/ID of the AI character to build scenario for")
    persona_id: str | None = Field(None, description="Optional persona ID currently selected by user")
    available_personas: list[PersonaSummary] = Field(default_factory=list, description="List of available personas")
    conversation_history: list[ChatMessageModel] = Field(default_factory=list, description="Previous conversation messages")
    processor_type: str = Field(default="claude", description="AI processor type to use")
    backup_processor_type: str | None = Field(None, description="Optional backup processor type")


class ScenarioCreationStreamEvent(BaseModel):
    """Stream event for interactive scenario creation."""

    type: str = Field(..., description="Event type: 'message', 'update', 'complete', 'error'")
    message: str | None = Field(None, description="AI message chunk to show in chat")
    updates: PartialScenario | None = Field(None, description="Updated scenario state")
    error: str | None = Field(None, description="Error message if type is 'error'")


class SaveScenarioRequest(BaseModel):
    """Request model for saving a completed scenario."""

    scenario: Scenario = Field(..., description="The scenario to save")
    scenario_id: str | None = Field(None, description="Optional scenario ID (generated if not provided)")


class SaveScenarioResponse(BaseModel):
    """Response model for saving a scenario."""

    scenario_id: str = Field(..., description="The saved scenario's ID")
    message: str = Field(default="Scenario saved successfully", description="Status message")


class ScenarioSummary(BaseModel):
    """Summary model for scenario listing with minimal data."""

    id: str = Field(..., description="Scenario ID")
    summary: str = Field(..., description="Scenario title/summary")
    character_ids: list[str] = Field(default_factory=list, description="NPC character IDs")
    ruleset_id: str = Field(default="", description="Ruleset ID")
    created_at: str = Field(..., description="Creation timestamp")
    updated_at: str = Field(..., description="Last update timestamp")


class ListScenariosResponse(BaseModel):
    """Response model for listing scenarios."""

    scenarios: list[ScenarioSummary] = Field(..., description="List of scenario summaries")


# --- Ruleset API models ---


class RulesetSummary(BaseModel):
    """Summary model for ruleset listing."""

    id: str
    name: str
    drive_count: int = 0
    skill_count: int = 0
    created_at: str = ""


class CreateRulesetRequest(BaseModel):
    """Request model for creating a ruleset."""

    ruleset: Ruleset


class WorldLoreSummary(BaseModel):
    """Summary model for world lore listing."""

    id: str
    name: str
    tags: list[str] = Field(default_factory=list)
    content_preview: str = Field(default="", description="First 100 chars of content")


class CreateWorldLoreRequest(BaseModel):
    """Request model for creating a world lore entry."""

    lore: WorldLore


# --- Session state API models ---


class SessionStateResponse(BaseModel):
    """Full session state response."""

    session_id: str
    world_state: WorldState
    turn_counter: int
    status: str
    character_states: dict[str, Any] = Field(default_factory=dict)
    narration_history: list[str] = Field(default_factory=list)


class SessionCharacterSummary(BaseModel):
    """Summary of a character's state in a session."""

    character_id: str
    character_name: str
    is_present: bool
    drives: dict[str, float] = Field(default_factory=dict)
    active_intent_goal: str | None = None


class TurnRequest(BaseModel):
    """Request model for executing a simulation turn."""

    session_id: str = Field(..., min_length=1, description="Session ID to execute turn in")
    user_input: str = Field(..., min_length=1, description="User's action/input text")
    input_type: str | None = Field(None, description="Optional pre-classified input type (action, relocation, time_skip)")
    processor_type: str = Field(default="google", description="Large model processor type")
    mini_processor_type: str | None = Field(default=None, description="Mini model processor type")
    backup_processor_type: str | None = Field(None, description="Optional backup processor type")
